### ISSUE TITLE
Lint check failed

### ISSUE THREAD

**Issue by wilsonwu** [sentinel-group/sentinel-dashboard-k8s-operator#18]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
```
  Running [/home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  Error: File is not `goimports`-ed (goimports)
  
  Error: issues found
  Ran golangci-lint in 34803ms
```

### Describe what you expected to happen
Fix it.

**Comment by wilsonwu** [comment]
@jnan806 could you help on this?

**Comment by jnan806** [comment]
Because of some code files should be re-formatted by goimports. Like following :
<img width="750" alt="image" src="https://user-images.githubusercontent.com/43714056/206080779-b0078ed3-5f64-4813-9092-91b0ac1d32e2.png">



And now the golangci-lint-action looks not provide more detail logs. 
I have commit an issue in the official issue list. refers to https://github.com/golangci/golangci-lint-action/issues/618
